name: MouBieHideEquipment

version: '${project.version}'
api-version: ${plugin.api.version}

main: com.moubiehideequipment.MouBieCat
depend: [ MouBieAPI ]

authors: [ MouBieCat ]
description: '${project.description}'

commands:
  MouBieHideEquipment:
    description: "為該插件的主要命令。"
    aliases: [mbhe]

permissions:
  MouBieHideEquipment.use:
    description: "該插件的基本權限。"

  MouBieHideEquipment.reload:
    description: "該插件重讀的權限。"