name: MouBieHideEquipment

version: ${project.version}
api-version: 1.16

main: moubiehideequipment.main.MouBieCat

authors: [ MouBieCat ]
description: "作為 MouBieCat 開發的功能，可以隱藏自己身上的裝備穿著。但僅限於在客戶端！"

commands:
  MouBieHideEquipment:
    description: "為該插件的主要命令。"
    aliases: [mbhe]

permissions:
  MouBieHideEquipment.use:
    description: "該插件的基本權限。"
